[[language]]
name = "toml"
auto-format = true

[[language]]
name = "nix"
auto-format = true
indent = { tab-width = 2, unit = "\t" }

[language-server]
[language-server.nil.config.nil.formatting]
command = ["nixfmt", "-q"]

[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "html"
auto-format = true
formatter = { command = 'npx', args = ["prettier", "--parser", "html"] }
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "json"
formatter = { command = 'npx', args = ["prettier", "--parser", "json"] }
auto-format = true
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "css"
formatter = { command = 'npx', args = ["prettier", "--parser", "css"] }
auto-format = true
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "javascript"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "typescript"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "svelte"
language-servers = [ "svelteserver" ]
